### ISSUE TITLE
Add some extra explanation to generating data with predict function with missing input

### ISSUE THREAD

**Issue by mgmverburg** [storopoli/Bayesian-Julia#16]
For the PPC using the predict, the way that works is now shown in the tutorial:
https://storopoli.io/Bayesian-Julia/pages/4_Turing/#prior_and_posterior_predictive_checks 

However, as became apparent on Slack, it might not be self-explanatory enough for people that encounter it a first time, so perhaps some extra explanation needs to be given at least for the fact why `:y` should be where it is in: `DynamicPPL.Model{(:y,)}`.

Because if one passes in multiple missing variables, e.g. s1 and s2, then this should become `DynamicPPL.Model{(:s1, :s2,)}` for example.

**Comment by storopoli** [comment]
Thanks, for the record (so I can record latter): We need a better explanation of how to do it, and what the lines of code, arguments etc mean. It is a little bit of hand-weaving now in the Tutorials...
