### ISSUE TITLE
Formula definition of p-value

### ISSUE THREAD

**Issue by marcora** [storopoli/Bayesian-Julia#35]
Given the definition of p-value and the fact that everywhere else in the book the letter D represents the observed data, I would propose - to avoid any confusion by the reader - to change the formula definition of p-value to $P(D* \mid H_0)$, where D* represents data at least as extreme as the observed data (D). The way it is written now $P(D \mid H_0)$ to me reads as if the p-value is the probability of the observed data given that the null hypothesis is true.

**Comment by storopoli** [comment]
I don't know. Is that confusing at all?
D* for me looks a lot nice Data proposed, like in a MCMC simulaton (where we have theta*).

**Comment by marcora** [comment]
D* was just an idea, but anything other than D would do (perhaps D^{or more
extreme}).

**Comment by storopoli** [comment]
Can you make a PR?

**Comment by marcora** [comment]
Sure

**Comment by storopoli** [comment]
closed by #36
