### ISSUE TITLE
Expect should be except?

### ISSUE THREAD

**Issue by alexbakus** [storopoli/Bayesian-Julia#37]
```# One-hot vector is a vector of integers in which all indices are zero (0) expect for one single index that is one (1).```

Should `expect` be replaced here with `except` ?

https://github.com/storopoli/Bayesian-Julia/blob/2da20a43a2cd5a550e68d78f47b52dc73246c50d/_literate/1_why_Julia.jl#L546

**Comment by storopoli** [comment]
Yes, it should. Can you please make a PR?

**Comment by storopoli** [comment]
closed by #38.
