### ISSUE TITLE
Gibbs sampler description

### ISSUE THREAD

**Issue by filchristou** [storopoli/Bayesian-Julia#49]
Hello and thank you very much for the excellent tutorial.

Currently you describe the iteration in the Gibbs sampler like the following:
![image](https://user-images.githubusercontent.com/27723218/176128565-30958cc4-0e52-4872-9be7-03a643f57eaa.png)

I had some trouble understanding it and when on Wikipedia there was a different form, which to a Bayesian beginner like myself made more sense :
https://en.wikipedia.org/wiki/Gibbs_sampling
![image](https://user-images.githubusercontent.com/27723218/176128777-1357a2c4-1c3e-44d3-8752-95523afe8dd8.png)

So I wonder if right-hand-side `t-1` is actually meant to be `t` and the right-hand-side `0` is meant to be `t` ?
Again, I don't mean to undermine your excellent work. Just trying to clear out any gray areas.
Thanks again!

**Comment by storopoli** [comment]
I made more simpler and less abstract than wikipedia.
I've explicitely set the `t` to be `0`, then the dots.

They are equivalent.
I've found that for beginners the way I've wrote makes more sense.
