### ISSUE TITLE
The second axiom of probability is false and the third one is fuzzy

### ISSUE THREAD

**Issue by empet** [storopoli/Bayesian-Julia#50]
The second axiom in your tutorial is stated as follows: *Additivity: For two mutually exclusive (events) A and B (cannot occur at the same time[9]): 
P(A) = 1 - P(B),  and P(B) = 1 - P(A)*.

Counterexample:
Let us consider the experiment of rolling a fair dice, A={3, 6},  the event to get a face divisible with 3,  and B={5}
the event to get the face 5. A and B are mutually exclusive.
P(A)=2/6=1/3, P(B)=1/6, but 1/3 is not equal to 1- 1/6.

Unfortunately you have taught this definition to your students, [https://storopoli.github.io/Estatistica-Bayesiana/0-Estatistica-Bayesiana.html#defini%C3%A7%C3%A3o-matem%C3%A1tica](https://storopoli.github.io/Estatistica-Bayesiana/0-Estatistica-Bayesiana.html#defini%C3%A7%C3%A3o-matem%C3%A1tica), whereas there are hundreds of books of probability, where you could have found  the right one :(
Also, I formulated the probability axioms when I opened the  thread on Julia discourse, related to your  chapter of Probability, you intended to introduce in Julia for Data Science, but it seems you did not read all comments in that thread :( 

I post here the definition of probability from the book, M. Baron - Probability and Statistics for Computer Scientists, Second edition, CRC Press. and from S. M. Ross, Probability Models for Computer Science, Academic Press:
![m-baron-def](https://user-images.githubusercontent.com/3627253/177056641-d15604d6-47b8-472d-a88b-ae99b97adeaf.png)
![sheldon-ross-def](https://user-images.githubusercontent.com/3627253/177056667-4501a97d-9b32-48b1-8960-9fe27be8b8b6.jpg)

So far, I've only  run a few Distributions and Turing examples, and can't yet  express an opinion.

**Comment by storopoli** [comment]
Thanks for the input, a PR and correction would be most welcome.

**Comment by empet** [comment]
I just made you aware of the definition flaws and now, you should correct it yourself, to keep a uniform style of the tutorial.
Moreover, since you persisted in keeping the wrong approach, discussed in [https://discourse.julialang.org/t/corrections-for-juliadatascience-book/69204](https://discourse.julialang.org/t/corrections-for-juliadatascience-book/69204) I'm really curious to see the right one, performed by the real author (in the discussion on that thread  I thought that the Probability chapter was created/edited by your co-author, but now it's clear that he just transcribed your approach.
