### ISSUE TITLE
Are joint probability distributions not always symmetric?

### ISSUE THREAD

**Issue by stelmo** [storopoli/Bayesian-Julia#56]
Hi, thanks for making this book, it is really helpful! I have question about a statement you make in [Chapter 2, equation 6](https://storopoli.github.io/Bayesian-Julia/pages/02_bayes_stats/#joint_probability). You say that in general P(A, K) != P(K, A). When is this not true in probability? Are there simple counter-examples?

**Comment by storopoli** [comment]
Actually joint probabilities are symmetric:

$$P(A, K) = P(K, A)$$

What I've said is that conditional probability is not commutative:

$$P(A \mid K) \ne P(K \mid A)$$

and that happens because base rates can differ:

$$P(A) \ne P(B)$$

**Comment by storopoli** [comment]
Example:

Probability of deadlifting 200 pounds given you are male is not the same as the probability of being male given you deaflift 200 pounds.

**Comment by stelmo** [comment]
Ah, thank you for clarifying!
