### ISSUE TITLE
chapter 10 duncans example  has problem

### ISSUE THREAD

**Issue by math4mad** [storopoli/Bayesian-Julia#61]
### example_-_duncans_prestige

`summarystats(chain) `    seems  use another datasets, cause rhat is  incorrect

copy-paste result is correct

**Comment by storopoli** [comment]
There could be slight changes in some parameter estimates and rhat calculations from different computers and runs. This is normal. The code runs in GitHub Actions so it might be a different set-up than your local machine.

**Comment by math4mad** [comment]
$\beta$[1]  's rhat= 23.8, $\beta$[2] 's rhat= 23.7.

**Comment by storopoli** [comment]
Oh yeah something funky is going on. Let me retrigger the CI build. We'll see.

**Comment by storopoli** [comment]
I cannot reproduce GitHub Actions output.
This is what I get:

```julia
Summary Statistics
  parameters      mean       std   naive_se      mcse         ess      rhat   ess_per_sec 
      Symbol   Float64   Float64    Float64   Float64     Float64   Float64       Float64 

          νₐ    5.1824    6.8002     0.1075    0.1445   2509.5600    1.0010       47.5404
          νᵦ    5.4047    6.3476     0.1004    0.1333   2401.0678    1.0007       45.4851
           α   -7.5277    3.0996     0.0490    0.0609   2800.7996    1.0000       53.0575
        β[1]    0.7717    0.1028     0.0016    0.0021   2029.8497    1.0003       38.4529
        β[2]    0.4448    0.0833     0.0013    0.0018   1767.3021    1.0010       33.4792
           σ    7.2534    1.8063     0.0286    0.0417   1721.7300    0.9995       32.6159
           ν    3.1185    3.4333     0.0543    0.0989   1600.4386    1.0013       30.3182
```

**Comment by storopoli** [comment]
I've simplified the model in #63. Let's see if that helps. Otherwise, it's up to GitHub Action machines to have a better mood on this specific model.
