### ISSUE TITLE
Robust regression

### ISSUE THREAD

**Issue by bdeonovic** [storopoli/Bayesian-Julia#7]
In the summary table for the robust regression example there are clearly some issues with the sampler as evidenced by the summary of beta[1]:

```
 std           naive_se                mcse         ess         rhat   ess_per_sec
      Symbol              Float64              Float64            Float64             Float64     Float64      Float64       Float64

           α               5.9437             177.6342             1.9860              4.7019   1682.7144       1.0096      115.0889
        β[1]   2918557377982.3223   5055405652489.1826   56521153464.0125   568742023576.1283     16.0321   23930.2360        1.0965
        β[2]              -4.9522              89.6014             1.0018              4.3793    411.7090       1.0080       28.1587
           ν               1.5936               3.6077             0.0403              0.1740     89.2368       1.1117        6.1033
          νᵦ               2.8181               5.0152             0.0561              0.2888     61.1063       1.1777        4.1793
          νₐ               4.5323               4.8496             0.0542              0.0832   3484.2626       1.0039      238.3054
           σ               5.2063               2.5503             0.0285              0.2357     23.2047       1.8193        1.5871
```

**Comment by storopoli** [comment]
@bdeonovic yeah I cannot reproduce it either in my Ubuntu Intel Notebook, Mac Mini Intel or MacBook Arm. This is something related to the GitHub Actions' Linux VMs that builds the and deploys the static site using the `.jl` literate notebooks in `_literalte/`.

Have you tried running the robust regression code on your local machine? I've tried to supply different seeds to the sampler to avoid this issue with GHA's VMs but to no avail.

Help would be most welcome

**Comment by storopoli** [comment]
I will rebuild the 9 robust regression with `seed!(456)` and we'll see how it will work out.

**Comment by bdeonovic** [comment]
perhaps its just the nature of the dataset coupled with these fat-tailed priors.
