### ISSUE TITLE
chapter 03: xlabel of many figures is wrong

### ISSUE THREAD

**Issue by rdiaz02** [storopoli/Bayesian-Julia#71]
For several of the distributions the xlabel is wrong, and should not be \theta:
- Binomial: should be `Number of events` or `Number of successes' 
- Poisson: should be `Number of events`
- NegativeBinomial: should be `Number of failures`
- Normal: should be `X` (or however one calls the random variable)
- etc

**Comment by storopoli** [comment]
Why can't we use simply Mass since we introduce $\text{PMF}$ in the beginning of the tutorial?

**Comment by storopoli** [comment]
Why cant' we abstract away and use only $\theta$?

**Comment by rdiaz02** [comment]
I think it is possibly confusing: $\theta$ is often used as a name for a parameter, but the X axes refer to specific random variables (not the parameter of the distribution). Moreover, these can be very different random variables; for example, the number of events in a Poisson, number of successes in a Binomial, number of failures in the negative binomial, etc. In addition, most of the descriptions do not mention any $\theta$ so it can make the reader wonder what is actually being represented.

(I understand, of course, it is a bit of a PITA to have to change the x axis label for each and every figure.)

**Comment by storopoli** [comment]
Yeah, a PR would be most welcome if you want to have it changed.
I am still not convinced that $\theta$ would be a source of confusion in the X-axis.
