### ISSUE TITLE
logistic regression error

### ISSUE THREAD

**Issue by spragud2** [storopoli/Bayesian-Julia#78]
Hey, 

I tried to run your log reg example using Julia 1.8.5, Turing v0.24.0, LazyArrays  v0.22.16 and get the following error:

```ERROR: ArgumentError: Broadcasted{Unknown} wrappers do not have a style assigned```

stemming from this line:

```
return y ~ arraydist(LazyArray( @~ BernoulliLogit.(α .+ X * β)))
```

Any thoughts? In the meanwhile I will just use the old syntax with a for loop but I imagine this implementation is faster?

Thanks!

**Comment by spragud2** [comment]
alright... wow, it didn't like taking a dataframe as input. Calling `Matrix(df)` fixed it

**Comment by storopoli** [comment]
OK glad it is now working
